name: Check Secret
on:
  workflow_call:
    outputs:
      has_secret:
        description: "True if the JULES_API_KEY is set"
        value: ${{ jobs.check.outputs.has_secret }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_secret: ${{ steps.check.outputs.has_secret }}
    steps:
      - id: check
        env:
          SECRET: ${{ secrets.JULES_API_KEY }}
        run: |
          if [[ "${{ github.actor }}" == "google-labs-jules[bot]" ]] || [[ "${{ github.actor }}" == "jules[bot]" ]]; then
            echo "has_secret=false" >> $GITHUB_OUTPUT
          elif [ -n "$SECRET" ]; then
            echo "has_secret=true" >> $GITHUB_OUTPUT
          else
            echo "has_secret=false" >> $GITHUB_OUTPUT
          fi
